name: test
description: A test app for Luhny.dart!
version: 1.0.0
homepage: https://github.com/angeldollface/luhny
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  luhny:
    git: git://github.com/angeldollface/luhny.dart.git