name: luhny
description: A Dart package to validate IMEI numbers of mobile devices.
version: 1.0.0
homepage: https://github.com/angeldollface/luhny.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  lints: ^2.0.1